### ISSUE TITLE
audio_example-DEMO_PDM_RECORD_PLAYBACK

### ISSUE THREAD

**Issue by Aztec02** [dialog-semiconductor/BLE_SDK10_examples#12]
**When trying to build the following case in audio_example:**
_#define DEMO_SELECTION                  DEMO_PDM_RECORD_PLAYBACK    (file: audio_task.h)_

**brings up the following error:**
_../audio_iface.c:32:34: error: 'sys_audio_pcm_specific_t {aka struct <anonymous>}' has no member named 'clk_generation'
                 device->pcm_param.clk_generation = HW_PCM_CLK_GEN_FRACTIONAL;_

**and indeed there is no field clk_generation in sys_audio_pcm_specific_t**.

By commenting out the lines that create the error the build can be completed successfully, but then there is an error when trying to execute the example. Specifically after recording the audio the code is stuck in the following assert:
sys_audio_mgr.c(line:255) --> initialize_pcm_reg --> case I2S_MODE: --> 
ASSERT_WARNING(param->total_channel_num == 2 * param->bits_depth / 8 );   

SDK_10.0.10.118 was used for the demonstration examples.

btw I see that there is an apu_demo project in the SDK that does pretty much the same things. What are the differences?

**Comment by kalamara** [comment]
Hello,
the example comes with an SDK patch, did you try to apply it ?
clk_generation is one of the reasons why it is necessary to apply the patch first. 
there are other things that will not work without the patch, as well.
Differences from the apu_demo include 
-this and other bugfixes,
-optimizations for power consumption,
-being able to playback a reference audio file (with apu_demo you can only record audio from the microphone, and then optionally play it back)
-but most importantly it supports DA7212, DA7213, DA7217, DA7218 CODECs with official release HAL drivers which the apu_demo does not include. 
In general the scope of the apu_demo was to demonstrate some audio functionality, while  the scope for this example was to showcase the usage of the DA721X  CODECs with the DA1469x.
I hope this helps,

**Comment by Aztec02** [comment]
I missed this one. 
I had done it by commenting out the error lines but now with the patch everything is built.

Thank you!
