### ISSUE TITLE
Link error in dlg_reset_info sample

### ISSUE THREAD

**Issue by choe-hyunho** [dialog-semiconductor/BLE_SDK10_examples#22]
Hi, teams.

When I tried to use dlg_reset_info (ADF) with BLE enabled project, **cmac_exception_ctx_ptr** symbol can't be found.
This symbol is not defined in current SDK version (10.0.10.118).

**Comment by jonkurtzjk** [comment]
Hi Choe-Hyunho, the cmac_exception_ctx_ptr, is unfortunately only available in upcoming releases of the SDK and there should have been a check for the SDK version number in here.  I will update the repo to compile this code out based on SDK versioning.  Thank you for reporting.

**Comment by blauret** [comment]
HI @choe-hyunho,

Thanks for reporting this one. It should be closed now. Please let us know if you still have any issues
