### ISSUE TITLE
IDE for DA14695 SDK

### ISSUE THREAD

**Issue by ramkumarkoppu** [dialog-semiconductor/BLE_SDK10_examples#24]
Hi,

I am new to Dialog eco system. just started evaluating DA14695. In the github repo readme file it says step 2: From the workspace you have setup go to File->Import
but did not specify what IDE this device needs for software development and how to get it if not already installed.

**Comment by ezflash** [comment]
HI @ramkumarkoppu ,

You should start with the [Getting Started Guide](http://lpccs-docs.dialog-semiconductor.com/um-b-090-da1469x_getting_started/index.html)

**Comment by ramkumarkoppu** [comment]
Getting Started Guide says this 
![image](https://user-images.githubusercontent.com/30557120/174590598-e875c29c-079c-461d-94b8-f948a227e720.png)
and when I click on SmartSnippets Studio User Manual link, I see just this 
![image](https://user-images.githubusercontent.com/30557120/174590742-08ded974-fc9d-4f13-9d16-1b780ad264a0.png)
It appears while transition from Dialog to Renesas it lost the required information. Has anyone from Dialog/Renesas can help here?

**Comment by blauret** [comment]
That's correct, the transition has created quite a few issues with the access to Dialog product. The transition took place last week and we are working to fix the problems. 

You can access the latest version to SmartSnippets Studio [here]([SmartSnippets Studio V2.0.20](https://www.renesas.com/us/en/document/sws/smartsnippets-studio-v2020-windows-os?language=en&r=1614971)).

The[ product page](https://www.renesas.com/us/en/products/interface-connectivity/wireless-communications/bluetooth-low-energy/da14691-multi-core-bluetooth-52-soc-system-power-management-unit#tab-field_tab_content_resources) is a good reference for resources access. Some of the resources are currently missing but as mentioned earlier we are working to fix that.

**Comment by ramkumarkoppu** [comment]
fix provided
